from appium.webdriver.common.appiumby import AppiumBy


class LookBy:
    ID = AppiumBy.ID
    ACCESSIBILITY_ID = AppiumBy.ACCESSIBILITY_ID
    XPATH = AppiumBy.XPATH
    IOS_PREDICATE = AppiumBy.IOS_PREDICATE
    IOS_CLASS_CHAIN = AppiumBy.IOS_CLASS_CHAIN
    ANDROID_UIAUTOMATOR = AppiumBy.ANDROID_UIAUTOMATOR
    ANDROID_VIEWTAG = AppiumBy.ANDROID_VIEWTAG
    ANDROID_DATA_MATCHER = AppiumBy.ANDROID_DATA_MATCHER
    ANDROID_VIEW_MATCHER = AppiumBy.ANDROID_VIEW_MATCHER
    IMAGE = AppiumBy.IMAGE
    CUSTOM = AppiumBy.CUSTOM
