class TimeOut:
    ONE_SECOND = 1
    TWO_SECONDS = 2
    THREE_SECONDS = 3
    FIVE_SECONDS = 5
    TEN_SECONDS = 10
    FIFTEEN_SECONDS = 15
    TWENTY_SECONDS = 20
    THIRTY_SECONDS = 30
    FORTY_SECONDS = 30
    ONE_MINUTE = 60
    TWO_MINUTES = 120
    FIVE_MINUTES = 300
    TEN_MINUTES = 600
